apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: gcr.io/google_containers/hyperkube:{{ kube_version }}
    command:
    - /hyperkube
    - controller-manager
    - --master=http://127.0.0.1:{{ kube_insecure_port }}
    - --service-account-private-key-file={{ host_key }}
    - --root-ca-file=/etc/pki/CA/ca.cert
    - --v={{ kube_log_level }}
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 1
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: etc-kubernetes
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: etc-kubernetes
  - name: etc-pki
    hostPath:
      path: /etc/pki
