---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  labels:
    app: kube-apiserver
    kubernetes.io/cluster-service: "true"
  name: kube-apiserver
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - targetPort: 8085
    port: 8086
    nodePort: 30001
  selector:
    app: kube-apiserver
